name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        node-version: ['14', '16', '18']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-asyncio

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint Python code
        run: |
          pip install black isort mypy
          black --check api_tester_mcp/
          isort --check-only api_tester_mcp/
          # mypy api_tester_mcp/ --ignore-missing-imports

      - name: Test Python package
        run: |
          python -c "import api_tester_mcp; print('Import successful')"
          python -m api_tester_mcp.server --help

      - name: Test npm package
        run: |
          node index.js --help
          node scripts/postinstall.js --help || true

      - name: Test installation
        run: |
          # Test the postinstall script works
          node scripts/postinstall.js
